// Journal articles. Blocks: p (paragraph), h (section heading), pull (pull quote),
// rule (numbered principle), look (render a look by id), specimen (live type).
import { site } from '../site.js';

export const articles = [
  {
    slug: 'pairing-a-display-serif',
    title: 'Pairing a display serif with a text face',
    deck: 'Two serifs on one page is not a mistake. It is a question of contrast, and contrast has more than one axis.',
    date: '2026-09-09',
    author: site.owner,
    face: 'kavorie/regular',
    faces: ['kavorie/regular', 'maroes/regular'],
    blocks: [
      { t: 'p', text: 'The old rule says pair a serif with a sans. It is a fine rule for beginners because it guarantees contrast. It is a limiting rule for everyone else, because the contrast it guarantees is the least interesting kind.' },
      { t: 'look', id: 'letters-before-sounds' },
      { t: 'h', text: 'Three axes of contrast' },
      { t: 'rule', n: '01', title: 'Stroke contrast', text: 'Kavorie is a high-contrast face: hairlines against heavy verticals. Maroes is moderate. Put them side by side and the eye reads the difference before it reads a single word.' },
      { t: 'rule', n: '02', title: 'Size', text: 'A display face needs to be displayed. Under forty pixels Kavorie loses its hairlines and starts to look like a bad copy of the text face. Give it size or leave it out.' },
      { t: 'rule', n: '03', title: 'Role', text: 'One face speaks, one face explains. If both try to speak, the page argues with itself. The deck and body belong to Maroes. Kavorie gets the headline and nothing else.' },
      { t: 'specimen', face: 'kavorie/regular', text: 'Hairlines against heavy verticals', size: 72 },
      { t: 'specimen', face: 'maroes/regular', text: 'Moderate contrast, built for the sentence after the headline.', size: 28 },
      { t: 'h', text: 'Where it fails' },
      { t: 'p', text: 'It fails when the sizes creep together. A 36 pixel Kavorie subhead over 24 pixel Maroes body is two serifs of similar weight fighting for the same job. Either push the subhead up to headline size or set it in Maroes and let the size step carry the hierarchy.' },
      { t: 'pull', text: 'One face speaks, one face explains.' },
      { t: 'p', text: 'This demo cut of Kavorie has letters only, which is a useful constraint. Headlines with no digits and no punctuation are usually better headlines.' },
    ],
  },
  {
    slug: 'duos-and-trios',
    title: 'When the pairing comes in the box',
    deck: 'Royal Fortune, Royal Maison and Maison Galliard ship as families of companions. What a designed set gives you, and what it still leaves to you.',
    date: '2026-09-09',
    author: site.owner,
    face: 'maison-galliard/serif',
    faces: ['royal-fortune/serif', 'royal-fortune/script', 'royal-maison/serif', 'royal-maison/script', 'maison-galliard/serif', 'maison-galliard/sans', 'maison-galliard/script'],
    blocks: [
      { t: 'p', text: 'Three families in the library arrive as sets. Two are serif and script duos, one is a serif, sans and script trio. Their designers have already solved the hardest part of pairing: the companions share x-height, stroke rhythm and a point of view.' },
      { t: 'look', id: 'galliard-house' },
      { t: 'h', text: 'What the set solves' },
      { t: 'p', text: 'Proportion. A script drawn to sit beside a specific serif will align at the baseline and match the serif in colour, meaning the overall darkness of a line. Pairing a script from one foundry with a serif from another, you spend an afternoon adjusting sizes to fake that. Here it is free.' },
      { t: 'look', id: 'fortune-and-grace' },
      { t: 'h', text: 'What it still leaves to you' },
      { t: 'rule', n: '01', title: 'Ratio', text: 'The script is almost always set smaller than it looks like it should be. In the invitation above, the script is two thirds of the serif size. Any larger and it stops being a whisper.' },
      { t: 'rule', n: '02', title: 'Quantity', text: 'One line of script per piece. The duo works because the script is rare. Two script lines and it becomes wallpaper.' },
      { t: 'rule', n: '03', title: 'The third voice', text: 'Duos have no body face. Royal Maison serif can carry a short menu, but for a paragraph you still need a text face from elsewhere. The trio solves this with its sans.' },
      { t: 'look', id: 'aperitivo' },
      { t: 'p', text: 'Maison Galliard is the most complete system here. Its sans is quiet enough for captions, its serif has real alternates, and the script matches both. If the brief is hospitality, it is the first thing to try.' },
    ],
  },
  {
    slug: 'playful-without-childish',
    title: 'Playful without childish',
    deck: 'Bhelmora and Mochi Pop are fun faces. The pairing decides whether the result is charming or a birthday card.',
    date: '2026-09-09',
    author: site.owner,
    face: 'bhelmora/regular',
    faces: ['bhelmora/regular', 'mochi-pop/regular', 'helvetica/rounded-bold', 'paperline/regular'],
    blocks: [
      { t: 'p', text: 'A playful display face is a strong flavour. The mistake is adding a second strong flavour. Playful headline plus handwritten body plus three colours is how packaging ends up looking like a school fete.' },
      { t: 'look', id: 'marmalade' },
      { t: 'rule', n: '01', title: 'One character, one straight man', text: 'Bhelmora bounces. Helvetica Rounded Bold does not. It is soft enough to belong and plain enough to let the display face be the joke.' },
      { t: 'rule', n: '02', title: 'Colour carries the mood', text: 'Mustard and brick red make the marmalade look edible before anyone reads a word. The type can afford to be simpler because the palette is doing the smiling.' },
      { t: 'look', id: 'mochi' },
      { t: 'rule', n: '03', title: 'Match the roundness', text: 'Mochi Pop is inflated. Pair it with a rounded sans, not a sharp one, or the body text looks like it wandered in from a different box.' },
      { t: 'h', text: 'The handwritten exception' },
      { t: 'p', text: 'Paperline is casual rather than playful. It works as a body voice for a card because it reads as a person, not a brand. But keep it away from Bhelmora and Mochi Pop. Two informal faces cancel each other out.' },
      { t: 'look', id: 'paperline' },
      { t: 'pull', text: 'Playful headline, plain body, one accent colour. That is the whole recipe.' },
    ],
  },
];

articles.push(
  {
    slug: 'six-elegant-pairings',
    title: 'Six elegant font pairings',
    deck: 'Elegant is a proportion, not a category. Six pairings from the library that earn the word, and the one rule each of them follows.',
    date: '2026-09-10',
    author: site.owner,
    face: 'auleriz/regular',
    faces: ['auleriz/regular', 'welorac/regular', 'kavorie/regular', 'maroes/regular', 'maison-celeste/regular', 'naolen/regular', 'helvetica/light', 'biora/regular', 'evo-rinnox/regular', 'qliesya/regular', 'hidda/regular'],
    blocks: [
      { t: 'p', text: 'Every elegant pairing here has a face with hairlines and a face without. The hairline face is the one you remember. The other one is the reason you could read the page.' },
      { t: 'h', text: '1. Auleriz and Welorac' },
      { t: 'look', id: 'auleriz-issue' },
      { t: 'rule', n: '01', title: 'Same studio, two volumes', text: 'Both come from Ermedia and share a stroke. Auleriz is tall and narrow, Welorac is set to read. The eye takes them as one voice.' },
      { t: 'h', text: '2. Kavorie and Maroes' },
      { t: 'look', id: 'letters-before-sounds' },
      { t: 'rule', n: '02', title: 'Contrast of stroke, not of category', text: 'Two serifs. Kavorie has hairlines against heavy verticals, Maroes is moderate. Keep a size gap of at least three to one.' },
      { t: 'h', text: '3. Maison Celeste and Maroes' },
      { t: 'look', id: 'celeste' },
      { t: 'rule', n: '03', title: 'Cool ground for hairlines', text: 'Very fine serifs need a pale, cool background and a generous size. Below that they look broken rather than delicate.' },
      { t: 'h', text: '4. Naolen and Helvetica Light' },
      { t: 'look', id: 'naolen-parfum' },
      { t: 'rule', n: '04', title: 'Tiny x-height means one word', text: 'Naolen reads as a monogram. Use it for the name and nothing else. Helvetica Light in wide-tracked capitals takes every other line.' },
      { t: 'h', text: '5. Biora and Evo Rinnox' },
      { t: 'look', id: 'biora-tag' },
      { t: 'rule', n: '05', title: 'The grotesk does the chores', text: 'Biora is letters only. Anything with a number, a comma or a sentence goes to the grotesk, and the tag still looks like one design.' },
      { t: 'h', text: '6. Qliesya and Hidda' },
      { t: 'look', id: 'qliesya-beauty' },
      { t: 'rule', n: '06', title: 'A sturdier serif underneath', text: 'When the display face is fragile, choose a text serif with some weight to it. Hidda holds the deck and body without competing.' },
      { t: 'pull', text: 'One hairline face per page. Everything else is there to be read.' },
    ],
  },
  {
    slug: 'playful-pairings',
    title: 'Five playful pairings that stay grown up',
    deck: 'Bhelmora, Mochi Pop, Moot Jungle, Barking at Stars and Femhitary, each with the plain partner that keeps the joke from wearing thin.',
    date: '2026-09-10',
    author: site.owner,
    face: 'moot-jungle/regular',
    faces: ['bhelmora/regular', 'mochi-pop/regular', 'moot-jungle/regular', 'barking-at-stars/regular', 'femhitary/regular', 'helvetica/rounded-bold', 'cocogoose/regular', 'helvetica/bold'],
    blocks: [
      { t: 'p', text: 'A playful display face is a single strong flavour. Every pairing below adds exactly one plain partner and one colour idea, and stops there.' },
      { t: 'look', id: 'marmalade' },
      { t: 'rule', n: '01', title: 'Bhelmora with Helvetica Rounded Bold', text: 'The rounded sans matches the softness of the display face without bouncing. Mustard and brick red do the smiling.' },
      { t: 'look', id: 'mochi' },
      { t: 'rule', n: '02', title: 'Mochi Pop with Helvetica Rounded Bold', text: 'Inflated letters need a rounded body face or the sentence looks like it wandered in from another box. Pink on pink, one accent.' },
      { t: 'look', id: 'moot-jungle' },
      { t: 'rule', n: '03', title: 'Moot Jungle with Helvetica Rounded Bold', text: 'Groovy faces want saturation. Deep green and mango, and nothing else on the can with personality.' },
      { t: 'look', id: 'barking-stars' },
      { t: 'rule', n: '04', title: 'Barking at Stars with Cocogoose', text: 'Two cuts of one playful family for headline and label, a geometric sans for the sentence. Cocogoose is round enough to belong and calm enough to read.' },
      { t: 'look', id: 'femhitary' },
      { t: 'rule', n: '05', title: 'Femhitary with Helvetica Bold', text: 'A brush script wants a bold, plain neighbour and one colour that argues back. Small caps keep it legible from across the street.' },
      { t: 'pull', text: 'Playful headline, plain body, one accent colour. That is the whole recipe.' },
    ],
  },
  {
    slug: 'signature-scripts',
    title: 'Signature scripts and what to put under them',
    deck: 'Sophia Oliver, Ronalltie, Daenerys, Bellique, Malograh and Paperline. A script is a name, and a name needs a second line.',
    date: '2026-09-10',
    author: site.owner,
    face: 'ronalltie/regular',
    faces: ['sophia-oliver/regular', 'ronalltie/regular', 'daenerys/regular', 'bellique/regular', 'malograh/regular', 'paperline/regular', 'auleriz/regular', 'helvetica/light', 'helvetica/regular', 'evo-rinnox/regular'],
    blocks: [
      { t: 'p', text: 'Scripts fail on the second line, not the first. The first line is the name and it looks wonderful. The second line is an address, a date, a tagline, and that is where the pairing gets decided.' },
      { t: 'h', text: 'Match the weight of the hairline' },
      { t: 'look', id: 'daenerys-card' },
      { t: 'rule', n: '01', title: 'Thin script, thin sans', text: 'Daenerys is extra thin. Helvetica Light matches the stroke, so the card reads as one weight with two speeds of handwriting.' },
      { t: 'look', id: 'signed' },
      { t: 'rule', n: '02', title: 'Bold script, regular sans in capitals', text: 'Bellique has real weight. Wide-tracked Helvetica capitals at a third of the size is the classic answer and it still works.' },
      { t: 'h', text: 'Match the height' },
      { t: 'look', id: 'ronalltie-atelier' },
      { t: 'rule', n: '03', title: 'Low x-height script, tall serif', text: 'Ronalltie sits low and swings high. Auleriz has the ascenders to keep the two lines in proportion.' },
      { t: 'look', id: 'sophia-oliver' },
      { t: 'rule', n: '04', title: 'One flourish per piece', text: 'Sophia Oliver over Auleriz, set small. The script is the invitation, the serif is the announcement, and the script is set smaller than feels right.' },
      { t: 'h', text: 'Casual scripts are body voices' },
      { t: 'look', id: 'malograh-note' },
      { t: 'look', id: 'paperline' },
      { t: 'rule', n: '05', title: 'Hand the numbers to the grotesk', text: 'Malograh and Paperline can carry a sentence. The moment there is an address, a date or a price, give it to Evo Rinnox or Helvetica Light.' },
      { t: 'pull', text: 'A script is a name. Choose the second line first.' },
    ],
  },
  {
    slug: 'posters-and-condensed-faces',
    title: 'Posters and the condensed face',
    deck: 'Further, Saneoz and Helvetica Compressed. Why tall faces belong on posters, and the one word each poster gets.',
    date: '2026-09-10',
    author: site.owner,
    face: 'further/regular',
    faces: ['further/regular', 'saneoz/regular', 'helvetica/compressed', 'maroes/regular', 'evo-rinnox/regular'],
    blocks: [
      { t: 'p', text: 'A condensed face packs more letters into a width, which is another way of saying it can be set bigger. On a poster that is the whole job. The mistake is using that room for a sentence.' },
      { t: 'look', id: 'further' },
      { t: 'rule', n: '01', title: 'One word, full width', text: 'Further at forty percent of the poster width. A serif body for contrast in texture, not just size, and one acid accent on black.' },
      { t: 'look', id: 'saneoz-match' },
      { t: 'rule', n: '02', title: 'Let the family carry the details', text: 'Saneoz has accents and digits, so the fixture, time and teams can stay in the same face at smaller sizes. The grotesk takes the sentence.' },
      { t: 'look', id: 'compressed-poster' },
      { t: 'rule', n: '03', title: 'The Swiss move', text: 'A compressed grotesk with a serif body: one word at maximum size, everything else set to be read. Red, black, off-white. It has not stopped working since 1960.' },
      { t: 'specimen', face: 'further/regular', text: 'FURTHER', size: 160 },
      { t: 'specimen', face: 'helvetica/compressed', text: 'CONCRETE', size: 140 },
      { t: 'pull', text: 'If the headline needs a second word, the poster needs a second draft.' },
    ],
  },
  {
    slug: 'wedding-suites',
    title: 'Five wedding suites from the library',
    deck: 'Royal Fortune, Sophia Oliver, Dolce and Amyara, Gondhe and Morige. An invitation, a menu, a save the date, and the rules that keep them from turning sugary.',
    date: '2026-09-10',
    author: site.owner,
    face: 'royal-fortune/serif',
    faces: ['royal-fortune/serif', 'royal-fortune/script', 'sophia-oliver/regular', 'dolce-amyara/regular', 'dolce-amyara/italic', 'ronalltie/regular', 'gondhe/regular', 'morige/regular', 'daenerys/regular', 'auleriz/regular', 'helvetica/light'],
    blocks: [
      { t: 'p', text: 'Wedding stationery is where scripts go to be overused. The suites below use one script line each, sometimes none, and let a serif do the announcing.' },
      { t: 'look', id: 'fortune-and-grace' },
      { t: 'rule', n: '01', title: 'The duo that ships together', text: 'Royal Fortune serif and script were drawn for each other. Set the script at two thirds of the serif size and centre everything.' },
      { t: 'look', id: 'sophia-oliver' },
      { t: 'rule', n: '02', title: 'Signature over a tall serif', text: 'Sophia Oliver and Auleriz. The script is the couple, the serif is the date. Keep the palette to paper, ink and one warm metal.' },
      { t: 'look', id: 'dolce-wedding' },
      { t: 'rule', n: '03', title: 'Upright and italic for the courses', text: 'Dolce and Amyara gives you a romantic serif in two cuts. The italic is what makes a menu read as a menu. One script line, with love, and no more.' },
      { t: 'look', id: 'gondhe-atelier' },
      { t: 'rule', n: '04', title: 'Swash faces are names', text: 'Gondhe has swashed capitals and no punctuation. It is for the two names on the front and nothing inside.' },
      { t: 'look', id: 'morige-invite' },
      { t: 'rule', n: '05', title: 'Grey for the modern couple', text: 'Morige, a whisper of Daenerys, and Helvetica capitals for the facts. Grey on grey is how a wedding invitation avoids looking like a wedding invitation.' },
      { t: 'pull', text: 'One script line per piece. The serif announces, the script signs.' },
    ],
  },
);

articles.push(
  {
    slug: 'merch-and-heavy-faces',
    title: 'Merch and the heavy faces',
    deck: 'Blackletter, slab, spikes and shards. Raquens, Nuega, Haveron, Silver Shard and Dh Alista Aghni, and the one neutral that keeps a shirt from becoming a poster.',
    date: '2026-09-10',
    author: site.owner,
    face: 'raquens/regular',
    faces: ['raquens/regular', 'nuega/regular', 'haveron/regular', 'silver-shard/regular', 'dh-alista-aghni/bold', 'helvetica/bold', 'helvetica/compressed', 'helvetica/regular', 'evo-rinnox/regular'],
    blocks: [
      { t: 'p', text: 'Heavy display faces are built to be seen from across a room. On merch they get one word and a great deal of empty cotton. Everything else is set in a neutral, and the neutral is usually Helvetica.' },
      { t: 'look', id: 'raquens-merch' },
      { t: 'rule', n: '01', title: 'Blackletter and Helvetica', text: 'The oldest letterforms and the most neutral, on one shirt. No colour, wide-tracked capitals under the gothic, and nothing else.' },
      { t: 'look', id: 'nuega-roast' },
      { t: 'rule', n: '02', title: 'Slab for the shout', text: 'Nuega takes the name, Helvetica Compressed the tasting notes, Helvetica Regular the facts. Three sans-ish voices at three widths, all upright.' },
      { t: 'look', id: 'haveron-metal' },
      { t: 'rule', n: '03', title: 'Spikes need black', text: 'Haveron on anything but black looks like a costume. One blood red and a compressed grotesk for the second line.' },
      { t: 'look', id: 'shard-esports' },
      { t: 'rule', n: '04', title: 'Shards need ice', text: 'Silver Shard on navy with ice blue. The grotesk with a full character set carries the schedule, because the display face has no accents.' },
      { t: 'look', id: 'alista-poster' },
      { t: 'rule', n: '05', title: 'One word when the cut is letters only', text: 'Dh Alista Aghni is letters only in the demo. That is not a limitation on a poster. It is the brief.' },
      { t: 'pull', text: 'One heavy word, a lot of empty cotton, and Helvetica for everything the word does not say.' },
    ],
  },
  {
    slug: 'the-neutral-body-face',
    title: 'The neutral body face',
    deck: 'Why Helvetica Light carries a third of the lookbook, when Evo Rinnox takes over, and when a serif body is the better neutral.',
    date: '2026-09-10',
    author: site.owner,
    face: 'helvetica/light',
    faces: ['helvetica/light', 'helvetica/regular', 'helvetica/rounded-bold', 'evo-rinnox/regular', 'maroes/regular', 'welorac/regular', 'hidda/regular'],
    blocks: [
      { t: 'p', text: 'Every look in this library has a face that speaks and a face that explains. The explaining face is chosen last and matters most, because it is the one people actually read.' },
      { t: 'h', text: 'Helvetica Light, the default' },
      { t: 'specimen', face: 'helvetica/light', text: 'Nine rooms above the harbour, breakfast until noon.', size: 34 },
      { t: 'rule', n: '01', title: 'Thin enough to disappear', text: 'Under an elegant serif or a hairline script, Light matches the stroke and gets out of the way. Regular would compete; Bold would win.' },
      { t: 'look', id: 'quiet-luxury' },
      { t: 'h', text: 'Evo Rinnox, when the body needs a full character set' },
      { t: 'specimen', face: 'evo-rinnox/regular', text: 'Made in small numbers from European linen. Wash cold, hang dry.', size: 34 },
      { t: 'rule', n: '02', title: 'A grotesk with more room', text: 'Evo Rinnox has accents, digits and two stylistic sets, and a slightly warmer construction. It takes over when the display face is a demo with letters only and the body has to carry everything.' },
      { t: 'look', id: 'biora-tag' },
      { t: 'h', text: 'Rounded Bold, for playful pages' },
      { t: 'rule', n: '03', title: 'Match the softness', text: 'Under Bhelmora, Mochi Pop or Moot Jungle, a rounded sans is the neutral. Regular Helvetica would look like a tax form next to a bubble face.' },
      { t: 'look', id: 'moot-jungle' },
      { t: 'h', text: 'When the neutral is a serif' },
      { t: 'specimen', face: 'maroes/regular', text: 'Set a paragraph at the size you will actually use, then read it aloud.', size: 34 },
      { t: 'rule', n: '04', title: 'Editorial pages want a text serif', text: 'Maroes, Welorac and Hidda are the serif neutrals. Under a display serif they read as the same voice at reading volume. Under a sans they add warmth.' },
      { t: 'look', id: 'letters-before-sounds' },
      { t: 'pull', text: 'Choose the explaining face last. It is the one people read.' },
    ],
  },
);

export const bySlug = Object.fromEntries(articles.map(a => [a.slug, a]));
export const articlesUsingFamily = famId => articles.filter(a => a.faces.some(f => f.startsWith(famId + '/')));
