// The lookbook. Each look is one pairing composed as a small piece of design.
// Copy is written to the character coverage of each cut: demo faces with letters only
// get headlines with letters only.
//
// faces: { display, accent?, body } are face ids from the manifest.
// layout: poster | editorial | card | label | split  (see components/Look.jsx)

export const looks = [
  {
    id: 'galliard-house',
    title: 'Galliard House',
    mood: 'Luxury hotel',
    layout: 'card',
    faces: { display: 'maison-galliard/serif', accent: 'maison-galliard/script', body: 'maison-galliard/sans' },
    palette: { paper: '#f1eadb', ink: '#1c1a16', accent: '#8b6b3e' },
    copy: {
      kicker: 'EST. 1924 · LISBON',
      accent: 'a quiet address',
      headline: 'Galliard House',
      body: 'Twelve rooms, one garden, breakfast until noon.',
    },
    notes: 'A trio does the pairing for you. Serif for the name, script for the whisper, sans for the facts. Keep the sans small and let the serif own the middle of the card.',
  },
  {
    id: 'fortune-and-grace',
    title: 'Eleanor & James',
    mood: 'Wedding invitation',
    layout: 'card',
    faces: { display: 'royal-fortune/serif', accent: 'royal-fortune/script', body: 'royal-fortune/serif' },
    palette: { paper: '#f7f2ea', ink: '#2a2520', accent: '#a3452f' },
    copy: {
      kicker: 'THE VILLA · LAKE COMO',
      accent: 'together with their families',
      headline: 'Eleanor & James',
      body: 'Saturday the fourth of October at five in the evening',
    },
    notes: 'The script is the invitation, the serif is the announcement. Set the script one size smaller than feels right, then centre everything and stop.',
  },
  {
    id: 'aperitivo',
    title: 'Aperitivo Hour',
    mood: 'Hotel bar menu',
    layout: 'label',
    faces: { display: 'royal-maison/serif', accent: 'royal-maison/script', body: 'royal-maison/serif' },
    palette: { paper: '#0f2a25', ink: '#e9e2d0', accent: '#c9a36b' },
    copy: {
      kicker: 'SINCE 1931',
      headline: 'ROYAL MAISON',
      accent: 'aperitivo hour',
      body: 'Negroni 14   Bellini 12   Americano 11',
    },
    notes: 'Dark green, gold rule, wide-tracked capitals. The script earns its place by being the only thing that is not symmetrical.',
  },
  {
    id: 'letters-before-sounds',
    title: 'Letters before sounds',
    mood: 'Magazine feature',
    layout: 'editorial',
    faces: { display: 'kavorie/regular', accent: 'maroes/regular', body: 'maroes/regular' },
    palette: { paper: '#f3efe7', ink: '#171411', accent: '#d5411b' },
    copy: {
      kicker: 'ISSUE FOUR · THE TYPE PAGES',
      headline: 'Letters before sounds',
      accent: 'On choosing a face for the way it holds a line',
      body: 'A typeface earns its place on the page in the second paragraph, long after the headline has done its job. Watch the rhythm of the stems and whether the word spaces read as pauses or holes.',
      body2: 'Set a paragraph at the size you will actually use, then read it aloud. If your eye trips, fix the leading before you blame the face.',
    },
    notes: 'High-contrast display serif over a quieter modern serif. Both are serifs, so contrast comes from size and weight of stroke, not from category.',
  },
  {
    id: 'quiet-luxury',
    title: 'Collection Nine',
    mood: 'Fashion lookbook',
    layout: 'split',
    faces: { display: 'annyra/regular', body: 'helvetica/light' },
    palette: { paper: '#e8e4dc', ink: '#1a1a1a', accent: '#6b6b6b' },
    tweak: { display: { fontSize: '9cqw', letterSpacing: '0.06em' } },
    copy: {
      kicker: 'AUTUMN WINTER',
      headline: 'ANNYRA',
      body: 'Collection nine. Wool, silk and the colour of rain. Shown in Milan, worn everywhere else.',
    },
    notes: 'A wide geometric sans wants space, so give it half the page. Helvetica Light stays out of the way. Grey on grey keeps the volume down.',
  },
  {
    id: 'apothecary',
    title: 'Apothecary',
    mood: 'Vintage label',
    layout: 'label',
    faces: { display: 'raventhorn/regular', accent: 'maroes/regular', body: 'maroes/regular' },
    palette: { paper: '#efe3c8', ink: '#2b1d12', accent: '#8a3b2a' },
    copy: {
      kicker: 'EST. 1887 · EDINBURGH',
      headline: 'Apothecary',
      accent: '& Curiosities',
      body: 'Tinctures, tonics and remedies of doubtful provenance',
    },
    notes: 'One ornamental face per label. Everything else is plain, centred and small. The frame is doing the Victorian work so the type does not have to.',
  },
  {
    id: 'marmalade',
    title: 'Marmalade on Sunday',
    mood: 'Small-batch packaging',
    layout: 'poster',
    faces: { display: 'bhelmora/regular', accent: 'bhelmora/regular', body: 'helvetica/rounded-bold' },
    palette: { paper: '#f7c948', ink: '#2a1e0f', accent: '#d1481f' },
    copy: {
      kicker: 'SMALL BATCH · No. 12',
      headline: 'Marmalade',
      accent: 'on Sunday',
      body: 'Seville oranges, cut thick. Made in a kitchen, not a factory.',
    },
    notes: 'Whimsical display faces need a friendly body, not a serious one. Rounded Bold matches the softness without competing for attention.',
  },
  {
    id: 'signed',
    title: 'Bellique Studio',
    mood: 'Photography logo',
    layout: 'card',
    faces: { display: 'bellique/regular', body: 'helvetica/regular' },
    palette: { paper: '#14120f', ink: '#f4efe6', accent: '#e0c58c' },
    copy: {
      kicker: 'PARIS · SINCE 2019',
      headline: 'Bellique',
      body: 'STUDIO PHOTOGRAPHY',
    },
    notes: 'Script logos live or die by what sits under them. Wide-tracked Helvetica capitals at a third of the size is the classic answer, and it still works.',
  },
  {
    id: 'celeste',
    title: 'Céleste',
    mood: 'Perfume campaign',
    layout: 'poster',
    faces: { display: 'maison-celeste/regular', accent: 'maroes/regular', body: 'maroes/regular' },
    palette: { paper: '#dfe3e6', ink: '#1e2328', accent: '#9a7b5a' },
    copy: {
      kicker: 'EAU DE PARFUM',
      headline: 'Céleste',
      accent: 'light and shadow',
      body: 'Iris, cold stone and a little smoke. Fifty millilitres.',
    },
    notes: 'Hairline serifs need a cool, pale ground and generous size. Maroes handles the sentence with digits spelled out, since it has none.',
  },
  {
    id: 'mofela-wordmark',
    title: 'Mofela',
    mood: 'Wordmark',
    layout: 'split',
    faces: { display: 'mofela/regular', body: 'helvetica/light' },
    palette: { paper: '#f3efe7', ink: '#171411', accent: '#1a4fd6' },
    copy: {
      kicker: 'IDENTITY',
      headline: 'Mofela',
      body: 'A ligature serif for names that deserve a flourish. Set large, set once, leave it alone.',
    },
    notes: 'Ligature faces are wordmark faces. Pick a word where the pairs land and let the sans carry every other line.',
  },
  {
    id: 'mochi',
    title: 'Mochi Pop',
    mood: 'Sweet packaging',
    layout: 'poster',
    faces: { display: 'mochi-pop/regular', accent: 'mochi-pop/regular', body: 'helvetica/rounded-bold' },
    palette: { paper: '#ffd6e0', ink: '#3a1d2b', accent: '#ff5c8a' },
    copy: {
      kicker: 'NEW FLAVOUR',
      headline: 'Mochi Pop',
      accent: 'strawberry milk',
      body: 'Soft, chewy, a little bit silly. Six pieces per box.',
    },
    notes: 'Bubble faces are already loud. Pink on pink, one accent, and a rounded body face keep it sweet instead of shouty.',
  },
  {
    id: 'further',
    title: 'Further',
    mood: 'Festival poster',
    layout: 'poster',
    faces: { display: 'further/regular', accent: 'further/regular', body: 'maroes/regular' },
    palette: { paper: '#111111', ink: '#f2f2f2', accent: '#c8ff3d' },
    tweak: {
      display: { fontSize: '42cqw', letterSpacing: '0.04em', lineHeight: 0.85 },
      accent: { fontSize: '16cqw', letterSpacing: '0.12em' },
    },
    copy: {
      kicker: 'NIGHTS 27.09 – 03.10',
      headline: 'FURTHER',
      accent: 'NEW MUSIC',
      body: 'Seven nights of new music in an old power station. Doors at eight.',
    },
    notes: 'Tall condensed sans wants the full width and a black ground. One acid accent and a serif body for contrast in texture, not just in size.',
  },
  {
    id: 'gondhe-atelier',
    title: 'Gondhe',
    mood: 'Atelier card',
    layout: 'card',
    faces: { display: 'gondhe/regular', body: 'helvetica/light' },
    palette: { paper: '#f4ede4', ink: '#2a2320', accent: '#b07a4a' },
    copy: {
      kicker: 'ATELIER · BY APPOINTMENT',
      headline: 'Gondhe',
      body: 'Couture alterations and made-to-measure',
    },
    notes: 'Swash faces are names, not sentences. This cut has no punctuation, so the sans takes every line that needs a comma.',
  },
  {
    id: 'classical',
    title: 'Chapter One',
    mood: 'Book opening',
    layout: 'editorial',
    faces: { display: 'classical-material/regular', accent: 'maroes/regular', body: 'maroes/regular' },
    palette: { paper: '#ede6d6', ink: '#241f1b', accent: '#7b2d26' },
    copy: {
      kicker: 'CHAPTER ONE',
      headline: 'The Material of Letters',
      accent: 'in which a pen angle becomes a typeface',
      body: 'Calligraphic serifs keep the memory of the broad nib: thick where the pen pulled down, thin where it moved across. Pair them with a face that forgot the pen entirely.',
      body2: 'Maroes is that face. Its modern proportions let the calligraphy read as the special thing on the page.',
    },
    notes: 'Two serifs, two histories. The contrast is between calligraphic and constructed, and it reads clearly at any size.',
  },
  {
    id: 'kuigaf',
    title: 'Kuigaf',
    mood: 'Editorial identity',
    layout: 'split',
    faces: { display: 'kuigaf/regular', body: 'helvetica/regular' },
    palette: { paper: '#f0e9df', ink: '#1b1815', accent: '#2f6b4f' },
    copy: {
      kicker: 'QUARTERLY · No. 3',
      headline: 'Kuigaf',
      body: 'Wedge serifs and a narrow stance. A headline face for publications that take themselves seriously but not solemnly.',
    },
    notes: 'A sharp display serif beside plain Helvetica. The sans is the control group. Whatever character you see is coming from the serif.',
  },
  {
    id: 'paperline',
    title: 'Paperline',
    mood: 'Stationery',
    layout: 'card',
    faces: { display: 'paperline/regular', body: 'helvetica/light' },
    palette: { paper: '#fbf7ef', ink: '#2c2622', accent: '#c26a3f' },
    copy: {
      kicker: 'STATIONERY · HAND LETTERED',
      headline: 'Paperline',
      body: 'Cards, captions and the note on the fridge',
    },
    notes: 'Casual scripts pair with light sans faces. Anything heavier makes the script look like a mistake.',
  },
];

export const byLook = Object.fromEntries(looks.map(l => [l.id, l]));
export const looksUsing = faceId => looks.filter(l => Object.values(l.faces).includes(faceId));
export const looksUsingFamily = famId => looks.filter(l => Object.values(l.faces).some(f => f.startsWith(famId + '/')));
