// The lookbook. Each look is one pairing composed as a small piece of design.
// Copy is written to the character coverage of each cut: demo faces with letters only
// get headlines with letters only.
//
// faces: { display, accent?, body } are face ids from the manifest.
// layout: poster | editorial | card | label | split  (see components/Look.jsx)

export const looks = [
  {
    id: 'galliard-house',
    title: 'Galliard House',
    mood: 'Luxury hotel',
    layout: 'card',
    faces: { display: 'maison-galliard/serif', accent: 'maison-galliard/script', body: 'maison-galliard/sans' },
    palette: { paper: '#f1eadb', ink: '#1c1a16', accent: '#8b6b3e' },
    copy: {
      kicker: 'EST. 1924 · LISBON',
      accent: 'a quiet address',
      headline: 'Galliard House',
      body: 'Twelve rooms, one garden, breakfast until noon.',
    },
    notes: 'A trio does the pairing for you. Serif for the name, script for the whisper, sans for the facts. Keep the sans small and let the serif own the middle of the card.',
  },
  {
    id: 'fortune-and-grace',
    title: 'Eleanor & James',
    mood: 'Wedding invitation',
    layout: 'card',
    faces: { display: 'royal-fortune/serif', accent: 'royal-fortune/script', body: 'royal-fortune/serif' },
    palette: { paper: '#f7f2ea', ink: '#2a2520', accent: '#a3452f' },
    copy: {
      kicker: 'THE VILLA · LAKE COMO',
      accent: 'together with their families',
      headline: 'Eleanor & James',
      body: 'Saturday the fourth of October at five in the evening',
    },
    notes: 'The script is the invitation, the serif is the announcement. Set the script one size smaller than feels right, then centre everything and stop.',
  },
  {
    id: 'aperitivo',
    title: 'Aperitivo Hour',
    mood: 'Hotel bar menu',
    layout: 'label',
    faces: { display: 'royal-maison/serif', accent: 'royal-maison/script', body: 'royal-maison/serif' },
    palette: { paper: '#0f2a25', ink: '#e9e2d0', accent: '#c9a36b' },
    copy: {
      kicker: 'SINCE 1931',
      headline: 'ROYAL MAISON',
      accent: 'aperitivo hour',
      body: 'Negroni 14   Bellini 12   Americano 11',
    },
    notes: 'Dark green, gold rule, wide-tracked capitals. The script earns its place by being the only thing that is not symmetrical.',
  },
  {
    id: 'letters-before-sounds',
    title: 'Letters before sounds',
    mood: 'Magazine feature',
    layout: 'editorial',
    faces: { display: 'kavorie/regular', accent: 'maroes/regular', body: 'maroes/regular' },
    palette: { paper: '#f3efe7', ink: '#171411', accent: '#d5411b' },
    copy: {
      kicker: 'ISSUE FOUR · THE TYPE PAGES',
      headline: 'Letters before sounds',
      accent: 'On choosing a face for the way it holds a line',
      body: 'A typeface earns its place on the page in the second paragraph, long after the headline has done its job. Watch the rhythm of the stems and whether the word spaces read as pauses or holes.',
      body2: 'Set a paragraph at the size you will actually use, then read it aloud. If your eye trips, fix the leading before you blame the face.',
    },
    notes: 'High-contrast display serif over a quieter modern serif. Both are serifs, so contrast comes from size and weight of stroke, not from category.',
  },
  {
    id: 'quiet-luxury',
    title: 'Collection Nine',
    mood: 'Fashion lookbook',
    layout: 'split',
    faces: { display: 'annyra/regular', body: 'helvetica/light' },
    palette: { paper: '#e8e4dc', ink: '#1a1a1a', accent: '#6b6b6b' },
    tweak: { display: { fontSize: '9cqw', letterSpacing: '0.06em' } },
    copy: {
      kicker: 'AUTUMN WINTER',
      headline: 'ANNYRA',
      body: 'Collection nine. Wool, silk and the colour of rain. Shown in Milan, worn everywhere else.',
    },
    notes: 'A wide geometric sans wants space, so give it half the page. Helvetica Light stays out of the way. Grey on grey keeps the volume down.',
  },
  {
    id: 'apothecary',
    title: 'Apothecary',
    mood: 'Vintage label',
    layout: 'label',
    faces: { display: 'raventhorn/regular', accent: 'maroes/regular', body: 'maroes/regular' },
    palette: { paper: '#efe3c8', ink: '#2b1d12', accent: '#8a3b2a' },
    copy: {
      kicker: 'EST. 1887 · EDINBURGH',
      headline: 'Apothecary',
      accent: '& Curiosities',
      body: 'Tinctures, tonics and remedies of doubtful provenance',
    },
    notes: 'One ornamental face per label. Everything else is plain, centred and small. The frame is doing the Victorian work so the type does not have to.',
  },
  {
    id: 'marmalade',
    title: 'Marmalade on Sunday',
    mood: 'Small-batch packaging',
    layout: 'poster',
    faces: { display: 'bhelmora/regular', accent: 'bhelmora/regular', body: 'helvetica/rounded-bold' },
    palette: { paper: '#f7c948', ink: '#2a1e0f', accent: '#d1481f' },
    copy: {
      kicker: 'SMALL BATCH · No. 12',
      headline: 'Marmalade',
      accent: 'on Sunday',
      body: 'Seville oranges, cut thick. Made in a kitchen, not a factory.',
    },
    notes: 'Whimsical display faces need a friendly body, not a serious one. Rounded Bold matches the softness without competing for attention.',
  },
  {
    id: 'signed',
    title: 'Bellique Studio',
    mood: 'Photography logo',
    layout: 'card',
    faces: { display: 'bellique/regular', body: 'helvetica/regular' },
    palette: { paper: '#14120f', ink: '#f4efe6', accent: '#e0c58c' },
    copy: {
      kicker: 'PARIS · SINCE 2019',
      headline: 'Bellique',
      body: 'STUDIO PHOTOGRAPHY',
    },
    notes: 'Script logos live or die by what sits under them. Wide-tracked Helvetica capitals at a third of the size is the classic answer, and it still works.',
  },
  {
    id: 'celeste',
    title: 'Céleste',
    mood: 'Perfume campaign',
    layout: 'poster',
    faces: { display: 'maison-celeste/regular', accent: 'maroes/regular', body: 'maroes/regular' },
    palette: { paper: '#dfe3e6', ink: '#1e2328', accent: '#9a7b5a' },
    copy: {
      kicker: 'EAU DE PARFUM',
      headline: 'Céleste',
      accent: 'light and shadow',
      body: 'Iris, cold stone and a little smoke. Fifty millilitres.',
    },
    notes: 'Hairline serifs need a cool, pale ground and generous size. Maroes handles the sentence with digits spelled out, since it has none.',
  },
  {
    id: 'mofela-wordmark',
    title: 'Mofela',
    mood: 'Wordmark',
    layout: 'split',
    faces: { display: 'mofela/regular', body: 'helvetica/light' },
    palette: { paper: '#f3efe7', ink: '#171411', accent: '#1a4fd6' },
    copy: {
      kicker: 'IDENTITY',
      headline: 'Mofela',
      body: 'A ligature serif for names that deserve a flourish. Set large, set once, leave it alone.',
    },
    notes: 'Ligature faces are wordmark faces. Pick a word where the pairs land and let the sans carry every other line.',
  },
  {
    id: 'mochi',
    title: 'Mochi Pop',
    mood: 'Sweet packaging',
    layout: 'poster',
    faces: { display: 'mochi-pop/regular', accent: 'mochi-pop/regular', body: 'helvetica/rounded-bold' },
    palette: { paper: '#ffd6e0', ink: '#3a1d2b', accent: '#ff5c8a' },
    copy: {
      kicker: 'NEW FLAVOUR',
      headline: 'Mochi Pop',
      accent: 'strawberry milk',
      body: 'Soft, chewy, a little bit silly. Six pieces per box.',
    },
    notes: 'Bubble faces are already loud. Pink on pink, one accent, and a rounded body face keep it sweet instead of shouty.',
  },
  {
    id: 'further',
    title: 'Further',
    mood: 'Festival poster',
    layout: 'poster',
    faces: { display: 'further/regular', accent: 'further/regular', body: 'maroes/regular' },
    palette: { paper: '#111111', ink: '#f2f2f2', accent: '#c8ff3d' },
    tweak: {
      display: { fontSize: '42cqw', letterSpacing: '0.04em', lineHeight: 0.85 },
      accent: { fontSize: '16cqw', letterSpacing: '0.12em' },
    },
    copy: {
      kicker: 'NIGHTS 27.09 – 03.10',
      headline: 'FURTHER',
      accent: 'NEW MUSIC',
      body: 'Seven nights of new music in an old power station. Doors at eight.',
    },
    notes: 'Tall condensed sans wants the full width and a black ground. One acid accent and a serif body for contrast in texture, not just in size.',
  },
  {
    id: 'gondhe-atelier',
    title: 'Gondhe',
    mood: 'Atelier card',
    layout: 'card',
    faces: { display: 'gondhe/regular', body: 'helvetica/light' },
    palette: { paper: '#f4ede4', ink: '#2a2320', accent: '#b07a4a' },
    copy: {
      kicker: 'ATELIER · BY APPOINTMENT',
      headline: 'Gondhe',
      body: 'Couture alterations and made-to-measure',
    },
    notes: 'Swash faces are names, not sentences. This cut has no punctuation, so the sans takes every line that needs a comma.',
  },
  {
    id: 'classical',
    title: 'Chapter One',
    mood: 'Book opening',
    layout: 'editorial',
    faces: { display: 'classical-material/regular', accent: 'maroes/regular', body: 'maroes/regular' },
    palette: { paper: '#ede6d6', ink: '#241f1b', accent: '#7b2d26' },
    copy: {
      kicker: 'CHAPTER ONE',
      headline: 'The Material of Letters',
      accent: 'in which a pen angle becomes a typeface',
      body: 'Calligraphic serifs keep the memory of the broad nib: thick where the pen pulled down, thin where it moved across. Pair them with a face that forgot the pen entirely.',
      body2: 'Maroes is that face. Its modern proportions let the calligraphy read as the special thing on the page.',
    },
    notes: 'Two serifs, two histories. The contrast is between calligraphic and constructed, and it reads clearly at any size.',
  },
  {
    id: 'kuigaf',
    title: 'Kuigaf',
    mood: 'Editorial identity',
    layout: 'split',
    faces: { display: 'kuigaf/regular', body: 'helvetica/regular' },
    palette: { paper: '#f0e9df', ink: '#1b1815', accent: '#2f6b4f' },
    copy: {
      kicker: 'QUARTERLY · No. 3',
      headline: 'Kuigaf',
      body: 'Wedge serifs and a narrow stance. A headline face for publications that take themselves seriously but not solemnly.',
    },
    notes: 'A sharp display serif beside plain Helvetica. The sans is the control group. Whatever character you see is coming from the serif.',
  },
  {
    id: 'paperline',
    title: 'Paperline',
    mood: 'Stationery',
    layout: 'card',
    faces: { display: 'paperline/regular', body: 'helvetica/light' },
    palette: { paper: '#fbf7ef', ink: '#2c2622', accent: '#c26a3f' },
    copy: {
      kicker: 'STATIONERY · HAND LETTERED',
      headline: 'Paperline',
      body: 'Cards, captions and the note on the fridge',
    },
    notes: 'Casual scripts pair with light sans faces. Anything heavier makes the script look like a mistake.',
  },
];

looks.push(
  {
    id: 'sophia-oliver',
    title: 'Sophia & Oliver',
    mood: 'Wedding signature',
    layout: 'card',
    faces: { display: 'sophia-oliver/regular', body: 'auleriz/regular' },
    palette: { paper: '#f6f1ea', ink: '#2b2622', accent: '#b5875a' },
    tweak: { display: { fontSize: '15cqw' } },
    copy: {
      kicker: 'SAVE THE DATE · JUNE 2027',
      headline: 'Sophia & Oliver',
      body: 'Request the pleasure of your company',
    },
    notes: 'A signature script over a tall elegant serif. Auleriz has the long ascenders to match the script energy without adding a second flourish.',
  },
  {
    id: 'nuega-roast',
    title: 'Heavy Roast',
    mood: 'Coffee bag',
    layout: 'label',
    faces: { display: 'nuega/regular', accent: 'helvetica/compressed', body: 'helvetica/regular' },
    palette: { paper: '#2b1d14', ink: '#f2e6d3', accent: '#e0a458' },
    copy: {
      kicker: 'SINGLE ORIGIN · 250 G',
      headline: 'HEAVY ROAST',
      accent: 'DARK CHOCOLATE, FIG, SMOKE',
      body: 'Roasted on Tuesdays in a shed behind the bakery',
    },
    notes: 'Slab for the shout, compressed grotesk for the tasting notes, plain Helvetica for the facts. Three sans-ish voices at three widths, all upright.',
  },
  {
    id: 'neuropolitical',
    title: 'Neuropolitical',
    mood: 'Tech launch',
    layout: 'poster',
    faces: { display: 'neuropolitical/regular', accent: 'evo-rinnox/regular', body: 'evo-rinnox/regular' },
    palette: { paper: '#0c0f14', ink: '#e8f0ff', accent: '#4fd1ff' },
    tweak: { display: { fontSize: '7.2cqw', letterSpacing: '0.06em', whiteSpace: 'nowrap' }, accent: { fontSize: '3.2cqw', fontVariantLigatures: 'none' }, body: { fontVariantLigatures: 'none' } },
    copy: {
      kicker: 'SERIES 2 · SHIPPING 2027',
      headline: 'NEUROPOLITICAL',
      accent: 'A geometric future beside a grotesk present',
      body: 'The body face keeps the launch page readable long after the headline has done its glowing.',
    },
    notes: 'Futuristic display faces date fast. Pair them with a plain grotesk so the page can be re-skinned later without a rewrite.',
  },
  {
    id: 'femhitary',
    title: 'Written fast',
    mood: 'Street food',
    layout: 'poster',
    faces: { display: 'femhitary/regular', accent: 'femhitary/regular', body: 'helvetica/bold' },
    palette: { paper: '#e63b2e', ink: '#fff4e6', accent: '#ffd84d' },
    copy: {
      kicker: 'FRIDAY NIGHT MARKET',
      headline: 'Hot & Fast',
      accent: 'no reservations',
      body: 'Twelve stalls, one queue, cash only. Bring napkins.',
    },
    notes: 'A brush script wants a bold, plain neighbour and one colour that argues back. Helvetica Bold in small caps keeps the poster legible from across the street.',
  },
  {
    id: 'saneoz-match',
    title: 'Saneoz',
    mood: 'Match poster',
    layout: 'poster',
    faces: { display: 'saneoz/regular', accent: 'saneoz/regular', body: 'evo-rinnox/regular' },
    palette: { paper: '#f4f1ea', ink: '#111111', accent: '#1f5fff' },
    tweak: { display: { fontSize: '30cqw', lineHeight: 0.85 }, accent: { fontSize: '10cqw' } },
    copy: {
      kicker: 'HOME · SATURDAY 15.00',
      headline: 'DERBY',
      accent: 'NORTH vs SOUTH',
      body: 'Gates open at one. Tickets at the ground and online.',
    },
    notes: 'Condensed faces earn their keep on a poster with one word. Saneoz has accents and digits, so the details can stay in the same family if needed.',
  },
  {
    id: 'auleriz-issue',
    title: 'Auleriz',
    mood: 'Beauty editorial',
    layout: 'editorial',
    faces: { display: 'auleriz/regular', accent: 'welorac/regular', body: 'welorac/regular' },
    palette: { paper: '#efe9e3', ink: '#231f1d', accent: '#9c6b5a' },
    tweak: { display: { fontSize: '12cqw' } },
    copy: {
      kicker: 'BEAUTY · THE SKIN ISSUE',
      headline: 'Slow mornings',
      accent: 'Four routines that take longer than they need to, on purpose',
      body: 'Auleriz and Welorac come from the same studio and share a stroke, so the contrast is in proportion alone: one is tall and narrow, the other is set to read.',
      body2: 'Keep the deck in the body face. Two display serifs on one page is one too many.',
    },
    notes: 'Same-foundry pairing. When two faces share a designer, they usually share a rhythm, and the eye reads them as one voice at two volumes.',
  },
);

looks.push(
  {
    id: 'naolen-parfum',
    title: 'Naolen',
    mood: 'Perfume label',
    layout: 'card',
    faces: { display: 'naolen/regular', body: 'helvetica/light' },
    palette: { paper: '#f2efe9', ink: '#1f1c1a', accent: '#8e7b64' },
    tweak: { display: { fontSize: '16cqw' } },
    copy: { kicker: 'EXTRAIT · 30 ML', headline: 'Naolen', body: 'Vetiver, white tea, warm stone' },
    notes: 'A serif with a tiny x-height reads as a monogram at any size. Give it the whole card and let a light sans carry the notes below in wide-tracked capitals.',
  },
  {
    id: 'biora-tag',
    title: 'Biora',
    mood: 'Fashion swing tag',
    layout: 'split',
    faces: { display: 'biora/regular', body: 'evo-rinnox/regular' },
    palette: { paper: '#e9e4dc', ink: '#191715', accent: '#a0522d' },
    tweak: { display: { fontSize: '13cqw' } },
    copy: { kicker: 'SPRING · LINEN', headline: 'Biora', body: 'Made in small numbers from European linen. Wash cold, hang dry, wear often.' },
    notes: 'Flared display serif for the name, a grotesk with a full character set for the care instructions. The grotesk does everything the demo serif cannot: digits, punctuation, sentences.',
  },
  {
    id: 'qliesya-beauty',
    title: 'The Glow Issue',
    mood: 'Beauty editorial',
    layout: 'editorial',
    faces: { display: 'qliesya/regular', accent: 'hidda/regular', body: 'hidda/regular' },
    palette: { paper: '#f5ece6', ink: '#2a2220', accent: '#b76e79' },
    tweak: { display: { fontSize: '13cqw' } },
    copy: {
      kicker: 'BEAUTY · No. 12',
      headline: 'The Glow Issue',
      accent: 'Skin first, everything else after',
      body: 'Qliesya has hairlines that vanish under forty pixels, so it stays in the headline. Hidda, a complete modern serif, takes the deck and the body.',
      body2: 'Two serifs, one page, no argument: the size gap is doing the work.',
    },
    notes: 'A fine elegant serif over a sturdier modern one. Same category, different weights of stroke. Dusty rose keeps it in the beauty aisle.',
  },
  {
    id: 'moot-jungle',
    title: 'Moot Jungle',
    mood: 'Juice can',
    layout: 'poster',
    faces: { display: 'moot-jungle/regular', accent: 'moot-jungle/regular', body: 'helvetica/rounded-bold' },
    palette: { paper: '#1c5a3c', ink: '#f6efc7', accent: '#ffb347' },
    tweak: { display: { fontSize: '17cqw' } },
    copy: { kicker: 'COLD PRESSED · 330 ML', headline: 'Jungle', accent: 'mango & lime', body: 'No sugar added. Shake it, the pulp is the point.' },
    notes: 'Groovy display faces want saturated colour and a rounded body face. Nothing else on the can should have personality.',
  },
  {
    id: 'barking-stars',
    title: 'Barking at Stars',
    mood: 'Kids app',
    layout: 'poster',
    faces: { display: 'barking-at-stars/regular', accent: 'barking-at-stars/straight', body: 'cocogoose/regular' },
    palette: { paper: '#1e1b4b', ink: '#fff7d6', accent: '#7dd3fc' },
    tweak: { display: { fontSize: '14cqw' } },
    copy: { kicker: 'AGES 4 TO 8', headline: 'Star Dogs', accent: 'LEVEL TWELVE', body: 'Fetch the comets before the moon goes to bed.' },
    notes: 'Two cuts of one playful family for headline and label, and a geometric sans for the sentence. Cocogoose is round enough to belong and calm enough to read.',
  },
  {
    id: 'ronalltie-atelier',
    title: 'Ronalltie',
    mood: 'Bridal atelier',
    layout: 'card',
    faces: { display: 'ronalltie/regular', body: 'auleriz/regular' },
    palette: { paper: '#f8f4ee', ink: '#2a2523', accent: '#c19a6b' },
    tweak: { display: { fontSize: '17cqw' } },
    copy: { kicker: 'BY APPOINTMENT · MILAN', headline: 'Ronalltie', body: 'Bridal couture and veils' },
    notes: 'A signature script with a low x-height needs a tall, thin serif under it. Auleriz has the ascenders to keep the two lines in proportion.',
  },
  {
    id: 'daenerys-card',
    title: 'Daenerys',
    mood: 'Business card',
    layout: 'split',
    faces: { display: 'daenerys/regular', body: 'helvetica/light' },
    palette: { paper: '#f3f1ec', ink: '#1b1b1b', accent: '#9a9a9a' },
    tweak: { display: { fontSize: '17cqw', lineHeight: 1 } },
    copy: { kicker: 'PHOTOGRAPHER', headline: 'Daenerys', body: 'Weddings, portraits and the occasional dog. Available for travel.' },
    notes: 'An extra-thin signature script beside Helvetica Light. Both are hairlines, so the card reads as one weight with two handwriting speeds.',
  },
  {
    id: 'malograh-note',
    title: 'Malograh',
    mood: 'Postcard back',
    layout: 'split',
    faces: { display: 'malograh/regular', body: 'evo-rinnox/regular' },
    palette: { paper: '#fbf8f1', ink: '#2b2a28', accent: '#3b6ea5' },
    tweak: { display: { fontSize: '16cqw', lineHeight: 1 } },
    copy: { kicker: 'SENT FROM LISBON', headline: 'Wish you were here', body: 'Handwritten script for the message, a plain grotesk for the address block. Nobody writes their own postcode in cursive.' },
    notes: 'Casual scripts belong on the message side. The moment there is an address, a date or a number, hand it to the grotesk.',
  },
  {
    id: 'compressed-poster',
    title: 'Helvetica Compressed',
    mood: 'Exhibition poster',
    layout: 'poster',
    faces: { display: 'helvetica/compressed', accent: 'helvetica/compressed', body: 'maroes/regular' },
    palette: { paper: '#f2f2ee', ink: '#111111', accent: '#e4002b' },
    tweak: { display: { fontSize: '26cqw', lineHeight: 0.9, letterSpacing: '-0.01em' }, accent: { fontSize: '7cqw' } },
    copy: { kicker: 'KUNSTHALLE · 12 MAY – 30 AUG', headline: 'CONCRETE', accent: 'SWISS POSTERS 1950 TO 1975', body: 'A survey of the grid, the grotesk and the colour red.' },
    notes: 'A compressed grotesk with a serif body is the classic Swiss poster move: one word at maximum size, everything else set to be read.',
  },
  {
    id: 'dolce-wedding',
    title: 'Dolce & Amyara',
    mood: 'Wedding menu',
    layout: 'label',
    faces: { display: 'dolce-amyara/regular', accent: 'ronalltie/regular', body: 'dolce-amyara/italic' },
    palette: { paper: '#fbf6ee', ink: '#3a2e2a', accent: '#b07a5a' },
    tweak: { display: { fontSize: '11cqw' }, accent: { fontSize: '9cqw' } },
    copy: { kicker: 'DINNER', headline: 'Amyara', accent: 'with love', body: 'Burrata and peach    Lamb with rosemary    Lemon tart' },
    notes: 'A romantic serif in upright and italic for the courses, a signature script for the one line that is allowed to be sentimental. The italic earns the menu its rhythm.',
  },
  {
    id: 'morige-invite',
    title: 'Morige',
    mood: 'Gallery opening',
    layout: 'card',
    faces: { display: 'morige/regular', accent: 'daenerys/regular', body: 'helvetica/regular' },
    palette: { paper: '#ecebe6', ink: '#1d1d1b', accent: '#5d5d58' },
    tweak: { display: { fontSize: '14cqw' }, accent: { fontSize: '9cqw' } },
    copy: { kicker: 'THURSDAY 7 PM · RSVP', headline: 'Morige', accent: 'you are invited', body: 'NEW WORKS ON PAPER' },
    notes: 'An elegant display serif, a whisper of script, and Helvetica capitals for the facts. Grey on grey keeps the invitation from looking like a wedding.',
  },
);

export const byLook = Object.fromEntries(looks.map(l => [l.id, l]));
export const looksUsing = faceId => looks.filter(l => Object.values(l.faces).includes(faceId));
export const looksUsingFamily = famId => looks.filter(l => Object.values(l.faces).some(f => f.startsWith(famId + '/')));
