// Generated by scripts/build-manifest.mjs. Do not edit.
import u0 from '../fonts/annyra/Annyra-Regular.ttf';
import u1 from '../fonts/helvetica/Helvetica-Light.ttf';
import u2 from '../fonts/helvetica/Helvetica-Regular.ttf';
import u3 from '../fonts/helvetica/Helvetica-Oblique.ttf';
import u4 from '../fonts/helvetica/Helvetica-Bold.ttf';
import u5 from '../fonts/helvetica/Helvetica-BoldOblique.ttf';
import u6 from '../fonts/helvetica/Helvetica-Compressed.otf';
import u7 from '../fonts/helvetica/Helvetica-RoundedBold.otf';
import u8 from '../fonts/kavorie/Kavorie-Demo-Regular.otf';
import u9 from '../fonts/maison-celeste/MaisonCeleste-Demo-Regular.ttf';
import u10 from '../fonts/maroes/Maroes-Regular.otf';
import u11 from '../fonts/mofela/Mofela-Demo-Regular.ttf';
import u12 from '../fonts/royal-fortune/RoyalFortune-Serif-Demo.ttf';
import u13 from '../fonts/royal-fortune/RoyalFortune-Script-Demo.ttf';
import u14 from '../fonts/royal-maison/RoyalMaison-Serif.ttf';
import u15 from '../fonts/royal-maison/RoyalMaison-Script.ttf';
export const faces = [
  { family: "tc-annyra-regular", url: u0, format: "truetype" },
  { family: "tc-helvetica-light", url: u1, format: "truetype" },
  { family: "tc-helvetica-regular", url: u2, format: "truetype" },
  { family: "tc-helvetica-oblique", url: u3, format: "truetype" },
  { family: "tc-helvetica-bold", url: u4, format: "truetype" },
  { family: "tc-helvetica-bold-oblique", url: u5, format: "truetype" },
  { family: "tc-helvetica-compressed", url: u6, format: "opentype" },
  { family: "tc-helvetica-rounded-bold", url: u7, format: "opentype" },
  { family: "tc-kavorie-regular", url: u8, format: "opentype" },
  { family: "tc-maison-celeste-regular", url: u9, format: "truetype" },
  { family: "tc-maroes-regular", url: u10, format: "opentype" },
  { family: "tc-mofela-regular", url: u11, format: "truetype" },
  { family: "tc-royal-fortune-serif", url: u12, format: "truetype" },
  { family: "tc-royal-fortune-script", url: u13, format: "truetype" },
  { family: "tc-royal-maison-serif", url: u14, format: "truetype" },
  { family: "tc-royal-maison-script", url: u15, format: "truetype" },
];
export function injectFontFaces() {
  if (document.getElementById("tc-fontfaces")) return;
  const css = faces.map(f => `@font-face{font-family:"${f.family}";src:url("${f.url}") format("${f.format}");font-display:block}`).join("\n");
  const el = document.createElement("style"); el.id = "tc-fontfaces"; el.textContent = css; document.head.appendChild(el);
}
